name: Test and Release
on:
  push:
    # branches:
    #   - main
jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    # environment: default

    permissions:
      # https://github.com/semantic-release/semantic-release/issues/2469
      contents: write # create releases
      issues: write # issue comments and labels
      pull-requests: write # ditto
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run CI script (tests)
        run: deno task ci

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: true
          coverage-summary-path: ./coverage/coverage-summary.json

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Create the badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GH_TOKEN_GISTS }}
          gistID: db6d371d39faab64858178a049c8e80b
          filename: jest-coverage-comment__main.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          # namedLogo: javascript

      - name: Build NPM package
        run: deno task build:npm

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install -g @sebbo2002/semantic-release-jsr
          npx semantic-release
