name: Test and Release
on:
  push:
    # branches:
    #   - main
jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    # environment: default

    permissions:
      # https://github.com/semantic-release/semantic-release/issues/2469
      contents: write # create releases
      issues: write # issue comments and labels
      pull-requests: write # ditto
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js (for semantic-release only)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run CI script (tests)
        run: deno task ci

      - name: Export coverage to LCOV format
        run: |
          for file in `grep -l '"url": "\\\n' cov_profile/*`; do rm $file; done
          deno coverage --lcov --output=info.lcov cov_profile/

      - name: Prepare packages for next step (remove after non-sha release)
        run: cd /home/runner/work/_actions/gaelgirodon/ci-badges-action && npm i -D @actions/core @actions/github @actions/glob
  
      - name: Upload coverage to gist
        uses: gaelgirodon/ci-badges-action@1.6.0
        with:
          gist-id: db6d371d39faab64858178a049c8e80b
          token: ${{ secrets.GH_TOKEN_GISTS }}

      - name: Build NPM package
        run: deno task build:npm

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install -D @sebbo2002/semantic-release-jsr
          rm package.json package-lock.json
          npx semantic-release
