name: schema-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "20 0,12 * * *"

jobs:
  schema-sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check for Discourse OpenAPI schema updates
        run: deno task schema:sync
