name: schema-sync

on:
  schedule:
    - cron: "20 0,12 * * *"

jobs:
  schema-sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile # optional, --immutable

      - name: Check for Discourse OpenAPI schema updates
        run: yarn schema:sync
